mappingproxy({
    'sort': <method 'sort' of 'list' objects>,
    '__ge__': <slot wrapper '__ge__' of 'list' objects>,
    '__len__': <slot wrapper '__len__' of 'list' objects>,
    'reverse': <method 'reverse' of 'list' objects>,
    '__iadd__': <slot wrapper '__iadd__' of 'list' objects>,
    '__imul__': <slot wrapper '__imul__' of 'list' objects>,
    '__rmul__': <slot wrapper '__rmul__' of 'list' objects>,
    '__lt__': <slot wrapper '__lt__' of 'list' objects>,
    'pop': <method 'pop' of 'list' objects>,
    '__eq__': <slot wrapper '__eq__' of 'list' objects>,
    '__mul__': <slot wrapper '__mul__' of 'list' objects>,
    '__init__': <slot wrapper '__init__' of 'list' objects>,
    '__doc__': "list() -> new empty list\nlist(iterable) -> new list initialized from iterable's items",
    'index': <method 'index' of 'list' objects>,
    'clear': <method 'clear' of 'list' objects>,
    '__hash__': None,
    '__iter__': <slot wrapper '__iter__' of 'list' objects>,
    'copy': <method 'copy' of 'list' objects>,
    '__reversed__': <method '__reversed__' of 'list' objects>,
    '__setitem__': <slot wrapper '__setitem__' of 'list' objects>,
    '__le__': <slot wrapper '__le__' of 'list' objects>,
    'append': <method 'append' of 'list' objects>,
    '__repr__': <slot wrapper '__repr__' of 'list' objects>,
    'count': <method 'count' of 'list' objects>,
    'extend': <method 'extend' of 'list' objects>,
    '__new__': <built-in method __new__ of type object at 0x10e46a210>,
    '__getattribute__': <slot wrapper '__getattribute__' of 'list' objects>,
    '__delitem__': <slot wrapper '__delitem__' of 'list' objects>,
    'remove': <method 'remove' of 'list' objects>,
    '__contains__': <slot wrapper '__contains__' of 'list' objects>,
    'insert': <method 'insert' of 'list' objects>,
    '__gt__': <slot wrapper '__gt__' of 'list' objects>,
    '__ne__': <slot wrapper '__ne__' of 'list' objects>,
    '__add__': <slot wrapper '__add__' of 'list' objects>,
    '__getitem__': <method '__getitem__' of 'list' objects>
})
